/*
 * ADC_Config.h
 *
 * Created: 7/27/2023 5:43:03 PM
 *  Author: ORABY
 */ 


#ifndef ADC_CONFIG_H_
#define ADC_CONFIG_H_

/*
*Configure the voltage reference
*Range:
*ADC_VOLTAGE_REF_AREF
*ADC_VOLTAGE_REF_AVCC
*ADC_VOLTAGE_REF_2_56V
*/
#define ADC_VOLTAGE_REF_SELECTOR_msk			ADC_VOLTAGE_REF_AVCC
#define ADC_VOLTAGE_REF_mv						5000
#define ADC_MAX_NUMBER_OF_STEPS					1024

/*
*Configure ADC adjustment
*Range:
*ADC_RIGHT_ADJUSTED
*ADC_LEFT_ADJUSTED
*/
#define ADC_ADJUSTEMENT_SELECTOR_msk				ADC_RIGHT_ADJUSTED

/*
*Configure ADC Mode
*Range:
*ADC_MODE_AUTO_TRIGGER
*ADC_MODE_SINGLE_CONVERSION
*/
#define ADC_MODE_SELECTOR							ADC_MODE_SINGLE_CONVERSION		

/*
*Configure ADC Prescaler
*Range:
*ADC_PRESCALER_clr_msk
*ADC_PRESCALER_2_msk
*ADC_PRESCALER_4_msk
*ADC_PRESCALER_8_msk
*ADC_PRESCALER_16_msk
*ADC_PRESCALER_32_msk
*ADC_PRESCALER_64_msk
*ADC_PRESCALER_128_msk
*/
#define ADC_PRESCALER_SELECTOR_msk					ADC_PRESCALER_128_msk

/*
*Configure ADC AUTOTRIGGER
*Range:
*ADC_AUTO_TRIG_SRC_clr_msk
*ADC_AUTO_TRIG_SRC_FREE_RUNNING_ms
*ADC_AUTO_TRIG_SRC_ANALOG_COMP_msk
*ADC_AUTO_TRIG_SRC_EXTI0_msk
*ADC_AUTO_TRIG_SRC_TIMER0_COMP_msk
*ADC_AUTO_TRIG_SRC_TIMER0_OVF_msk
*ADC_AUTO_TRIG_SRC_TIMER1_COMP_msk
*ADC_AUTO_TRIG_SRC_TIMER1_OVF_msk
*ADC_AUTO_TRIG_SRC_TIMER1_CAPT_msk
*/
#define ADC_AUTO_TRIG_SRC_SELECTOR_msk			ADC_AUTO_TRIG_SRC_FREE_RUNNING_msk
	
#endif /* ADC_CONFIG_H_ */